apiVersion: v1
kind: Config
clusters:
- name: sw-k8s-cluster
  cluster:
    certificate-authority-data: <CERTIFICATE_AUTHORITY_DATA>
    server: https://10.0.4.90:7443
users:
- name: hyperaccel-<TEAM_NAME>-<USER_NAME>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubelogin
      args:
        - get-token
        - --grant-type=device-code
        - --oidc-issuer-url=https://login.microsoftonline.com/4c64662e-2a3e-4978-9437-2dcbcaf8beb7/v2.0
        - --oidc-client-id=213d0b12-cc00-4b46-a912-2b3c39d34713
        - --oidc-extra-scope=openid,profile,email,offline_access
        - --token-cache-dir=~/.kube/cache/kubelogin
contexts:
- name: sw-k8s-context
  context:
    cluster: sw-k8s-cluster
    user: hyperaccel-<TEAM_NAME>-<USER_NAME>
    namespace: hyperaccel-<TEAM_NAME>-ns
current-context: sw-k8s-context
